Provide commands to get AEM status information (SKYOPS-36712/SKYOPS-54405)
adobe/aio-cli-plugin-aem-rde pull request #46
Opened 2023-08-25 13:50 UTC by nonanalou

## Description
Provide commands to get AEM status information.

**USAGE**
```
$ aio aem rde inspect COMMAND
```
**TOPICS**
 ` aem rde inspect request-logs ` Get the list of request-logs for the target of a rapid development environment.

**COMMANDS**
` aem rde inspect setup `             Set the authorization token for all the inpect comands.
` aem rde inspect inventory `             Get the list of inventories for the target of a rapid development environment.
` aem rde inspect logs`                        Get the list of logs for the target of a rapid development environment.
` aem rde inspect osgi-bundles`         Get the list of osgi-bundles for the target of a rapid development environment.
` aem rde inspect osgi-components`  Get the list of osgi-components for the target of a rapid development environment.
`aem rde inspect osgi-configurations`  Get the list of osgi-configurations for the target of a rapid development environment.
`aem rde inspect osgi-services`        Get the list of osgi-services for the target of a rapid development environment.
`aem rde inspect request-logs`         Get the list of request-logs for the target of a rapid development environment.
`aem rde inspect sling-requests`       Get the list of sling-requests for the target of a rapid development environment.

## Related Issue
[SKYOPS-54405](https://jira.corp.adobe.com/browse/SKYOPS-54405) Enable aio authentication for AEM requests
[SKYOPS-36712](https://jira.corp.adobe.com/browse/SKYOPS-36712) Provide API for AEM status information

## Motivation and Context

## How Has This Been Tested?

`npm test`

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-09-12 14:37 UTC, jsedding requested changes
@nonanalou The PR looks good! I left a few comments, could you please check them? Thanks!

2023-09-12 14:37 UTC, jsedding commented on README.md
> +### Enable `aio aem rde inspect` commands
Either remove this section or add a fat warning that experimental features may not work, may not (yet) be available and may be removed without notice.

2023-09-12 14:37 UTC, jsedding commented on package.json
>      "bin": "aio",
You need to mark "aem:rde:inspect" as an experimental feature.

```suggestion
    "bin": "aio",
    "experimental-features": ["aem:rde:inspect"], 
```

2023-09-12 14:37 UTC, jsedding commented on package.json
>        "aem:rde": {
Please add a description for the "aem:rde:inspect" topic. Currently, I get the description of the "aem:rde:inspect:inventory" command when running `aio aem rde` (default must be the description of the first command?).

2023-09-12 15:31 UTC, nonanalou commented on README.md
> +### Enable `aio aem rde inspect` commands
Reloved: [692fc0b](https://github.com/adobe/aio-cli-plugin-aem-rde/pull/46/commits/692fc0b8dc6146f9de114c9e9b4d697ca059ed17)

2023-09-12 16:55 UTC, nonanalou commented on package.json
>        "aem:rde": {
Resolved: [a71ffc5](https://github.com/adobe/aio-cli-plugin-aem-rde/pull/46/commits/a71ffc521adb776ea74e8665845622cfb6cd97a5)

2023-09-12 16:57 UTC, nonanalou commented on package.json
>      "bin": "aio",
@jsedding should i already enable it? because like that it is not enabled for me.

2023-09-13 06:54 UTC, jsedding commented on package.json
>        "aem:rde": {
Thank you!

2023-09-13 06:55 UTC, jsedding commented on package.json
>      "bin": "aio",
No, it should not yet be enabled by default.

2023-09-13 06:57 UTC, jsedding approved these changes
Thanks for addressing my comments! It looks good now!

2023-09-14 09:45 UTC, merged