Skyops 84421 snapshots
adobe/aio-cli-plugin-aem-rde pull request #98
Opened 2024-09-23 13:19 UTC by RemoLiechti

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2025-05-21 13:13 UTC, sabdouni commented
Hello,

Thanks for all the good work on this PR.
Is there an ETA for the release of this feature?
Thanks

2025-05-21 13:36 UTC, RemoLiechti commented
> Hello,
> 
> Thanks for all the good work on this PR. Is there an ETA for the release of this feature? Thanks

Hi @sabdouni there is no official GA announced yet. It is still work in progress, but it should be available close future.

2025-07-29 08:47 UTC, RemoLiechti commented
hi @sabdouni 
seems like you are interested in this work. Please reach out to me(Slack, MS Teams or email) in case you want to test this in the early access program, we might be able to work something out.

2025-09-08 09:15 UTC, jsedding requested changes
Just a few small cleanups.

2025-09-08 09:15 UTC, jsedding commented on src/commands/aem/rde/clean.js
> +});
Can we remove this (in case we don't delete the whole command implementation?

2025-09-08 09:15 UTC, jsedding commented on package.json
> +      "aem:rde:snapshot"
Please add `aem:rde:clean` to this list.

2025-09-08 09:15 UTC, jsedding commented on src/commands/aem/rde/clean.js
> +class CleanEnvrionment extends BaseCommand {
Please remove the "clean" command.

2025-09-08 09:22 UTC, RemoLiechti commented on src/commands/aem/rde/clean.js
> +class CleanEnvrionment extends BaseCommand {
wiped

2025-09-08 09:23 UTC, RemoLiechti commented on package.json
> +      "aem:rde:snapshot"
nope, wiped the clean command instead

2025-09-08 09:23 UTC, RemoLiechti commented on src/commands/aem/rde/clean.js
> +});
nope, wiped the clean command instead

2025-09-08 09:27 UTC, jsedding approved these changes

2025-09-08 09:29 UTC, merged